name: Reusable HTTP Call Workflow

on:
  # 允许此工作流被其他工作流调用
  workflow_call:
    inputs:
      service_name:
        description: '需要调用的服务名称'
        required: true
        type: string
      branch_name:
        description: '相关的分支名称'
        required: true
        type: string
      github_actor:
        description: '推送人 GitHub 账号'
        required: true
        type: string

  # 允许此工作流从 Actions 标签页手动触发
  workflow_dispatch:
    inputs:
      service_name:
        description: '需要调用的服务名称'
        required: true
        type: string
      branch_name:
        description: '相关的分支名称'
        required: true
        type: string
      github_actor:
        description: '推送人 GitHub 账号'
        required: true
        type: string

jobs:
  make-http-call:
    name: Make HTTP Call
    runs-on: ubuntu-latest
    steps:
      - name: Display input parameters
        run: |
          echo "Service Name: ${{ inputs.service_name }}"
          echo "Branch Name: ${{ inputs.branch_name }}"
          echo "Actor Name: ${{ inputs.github_actor }}"
          
      - name: Perform HTTP Call
        run: |
          # 使用 secret 进行认证，并使用 inputs 构建请求体
          curl -v --location --request POST 'https://octopipe.k8s.shub.us/github/allocator' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "service_name": "${{ inputs.service_name }}",
              "branch_name": "${{ inputs.branch_name }}",
              "github_actor": "${{ inputs.github_actor }}"
          }'
